version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5001:5001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - FLASK_ENV=development
      - DOCKER_HOST=unix:///var/run/docker.sock
    networks:
      - appstore_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    depends_on:
      - api
    networks:
      - appstore_network

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - appstore_network

networks:
  appstore_network:
    name: appstore_network
    external: true
