version: '1'
services:
  app:
    image: appstore
    ports:
      - 5001:5000
    volumes:
      - ./app:/app
    environment:
      - ENV_VARIABLE=value
  trapper:
    image: registry.gitlab.com/trapper-project/trapper:latest
    