from .main import bp as main_bp
from .zamba import bp as zamba_bp
from .trapper import bp as trapper_bp
from .animl import bp as animl_bp
from .megadetector import bp as megadetector_bp
from .ecosecrets import bp as ecosecrets_bp
from .il2bb import bp as il2bb_bp
from .cameraTrapTools import bp as camera_trap_tools_bp
from .wildCoFaceBlur import bp as wildCoFaceBlur_bp
from .dataSpace import bp as dataSpace_bp
from .cameraTrapWorkflow import bp as cameraTrapWorkflow_bp
